# Generated by Django 2.1.5 on 2019-02-01 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('license', models.CharField(max_length=10)),
                ('vehicle_level', models.CharField(choices=[('S', '1-3 people'), ('M', '1-5 people'), ('L', '1-7 people')], default='S', max_length=1)),
                ('special_service', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=200)),
                ('passenger_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('arrival_time', models.DateTimeField()),
                ('vehicle_level', models.CharField(choices=[('S', '1-3 people'), ('M', '1-5 people'), ('L', '1-7 people')], default='S', max_length=1)),
                ('passenger_num', models.IntegerField()),
                ('is_shared', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Open', 'Order is open'), ('Canceled', 'Order is canceled'), ('Confirmed', 'Order is confirmed'), ('Finished', 'Order is finished')], default='Canceled', max_length=10)),
                ('special_request', models.CharField(blank=True, max_length=200, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myride.Driver')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myride.Ride'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myride.Customer'),
        ),
    ]
