# Generated by Django 2.1.5 on 2019-02-06 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myride', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.RemoveField(
            model_name='driver',
            name='name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='phone',
        ),
    ]
