# Generated by Django 2.1.5 on 2019-02-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myride', '0002_auto_20190206_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='isdriver',
            field=models.BooleanField(default=False),
        ),
    ]
